services:
  app:
    build: .
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - .:/kaggle/working
    working_dir: /kaggle/working
    shm_size: '2g'
    tty: true